name: Docker Image CI

on:
  push:
    branches: [ "v*", "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "v*", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/0xfacet/facet-node
        tags: |
          type=ref,event=branch  # Creates tags for branches (v1.0.0, main)
          type=sha,format=short  # Creates short SHA tags
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}  # Only tag latest from main branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
